version: '3'
services:
  nestjs-app:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASS}
      PG_DB: ${PG_DB}
    ports:
      - 5432:5432